### ISSUE TITLE
update to Gradle 7.1 fails from 7.0.2

### ISSUE THREAD

**Issue by BigMichi1** [gradle-update/update-gradle-wrapper-action#233]
currently my project is on Gradle 7.0.2

the Github action now fails when it wants to upgrade to version 7.1

as far as I understand whats going on here is that with the command
 `/usr/bin/gradle wrapper --gradle-version 7.1 --distribution-type all --gradle-distribution-sha256-sum a9e356a21595348b6f04b024ed0b08ac8aea6b2ac37e6c0ef58e51549cd7b9cb`
only the `gradle.properties` file is updated and so the check of the `gradle-wrapper.jar` file fails with 
```
  /usr/bin/sha256sum /home/runner/work/gradle-dependency-analyze/gradle-dependency-analyze/gradle/wrapper/gradle-wrapper.jar
  e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637  /home/runner/work/gradle-dependency-analyze/gradle-dependency-analyze/gradle/wrapper/gradle-wrapper.jar
  ##[debug]SHA-256: e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637
  Error: ❌ SHA-256 Wrapper jar mismatch
```
here the hash of the "old" 7.0.2 version is returned.

when I run the commands locally, especially the `git diff --name-only` immediately after the above command only one file change is listed, which is the one mentioning that `gradle-wrapper.properties` has been changed

this explains the wrong hash of the jar file

when I run the wrapper command twice instead of one time then the git command lists three changed files 
```
gradle/wrapper/gradle-wrapper.jar
gradle/wrapper/gradle-wrapper.properties
gradlew
```

looks like related wrapper files are only updated with the wrapper task when the "new" version is used to execute the wrapper task

can this be fixed?

**Comment by cristiangreco** [comment]
Thanks so much for reporting this issue @BigMichi1! I believe this is now fixed.

I've released a new version and updated the `v1` tag: changes should be picked up on your next run (let me know if that's not the case).
