### ISSUE TITLE
Custom Commit Message.

### ISSUE THREAD

**Issue by lizhongyue248** [gradle-update/update-gradle-wrapper-action#246]
My company project's commit message is [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

So, I want the upgrade message is `chore(deps):  Update Gradle Wrapper from 7.0.2 to 7.1. `.

And my personal project's commit message is [Gitmoji](https://gitmoji.dev/), I want the commit message is `:arrow_up: Update Gradle Wrapper from 7.0.2 to 7.1. `.

Or other language... Like `chore(deps): Gradle Wrapper 版本升级 7.0.2 => 7.1。`.

But now, the commit message must be `Update Gradle Wrapper from 7.0.2 to 7.1.`.

I have to modify it manually, like `rebase`. It bothers me a lot. T T...

How do I custom commit message?

**Comment by ChrisCarini** [comment]
I, too, would love to see this feature.

**Comment by paulschuberth** [comment]
In case anybody is still interested in this issue, I've opened PR #679 for this.

**Comment by cristiangreco** [comment]
Hi, https://github.com/gradle-update/update-gradle-wrapper-action/pull/679 is now finally merged and included in v2. Thanks so much for your help and patience!
