### ISSUE TITLE
I see no action running

### ISSUE THREAD

**Issue by hannesa2** [gradle-update/update-gradle-wrapper-action#25]
I tried out this, but on an unknown reason there was no job started.

Inspired by https://github.com/ytai/ioio/pull/208 I made this changes on an other repo https://github.com/MikeOrtiz/TouchImageView/blob/master/.github/workflows/update-gradle-wrapper.yml where I expect an update from `6.6 `to `6.6.1`

But to action was started https://github.com/MikeOrtiz/TouchImageView/actions?query=workflow%3A%22Update+Gradle+Wrapper%22 

Do you have an idea why nothing happens ?

**Comment by hannesa2** [comment]
I see, it uses GMT time 👍 
https://github.com/MikeOrtiz/TouchImageView/pull/282.

But I guess my actions have a wrong trigger 
<img width="261" alt="image" src="https://user-images.githubusercontent.com/3314607/95048862-e9d28780-06e8-11eb-95e2-6186020b9c8d.png">

because CI was not started on the sheduled action. This is a requirement !

**Comment by cristiangreco** [comment]
> I see, it uses GMT time 👍
> [MikeOrtiz/TouchImageView#282](https://github.com/MikeOrtiz/TouchImageView/pull/282).

Yep, GitHub cron schedules are UTC based, see [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events).


> But I guess my actions have a wrong trigger
> <img alt="image" width="261" src="https://user-images.githubusercontent.com/3314607/95048862-e9d28780-06e8-11eb-95e2-6186020b9c8d.png">
> 
> because CI was not started on the scheduled action. This is a hard requirement !

It is just a matter of changing the `repo-token` value used, see [this reply](https://github.com/ytai/ioio/pull/208#issuecomment-703520641).

> When I delete [MikeOrtiz/TouchImageView#282](https://github.com/MikeOrtiz/TouchImageView/pull/282) does it generate a new pull request ?

Yes, and make sure to delete the branch as well.
