### ISSUE TITLE
Exclude a path?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle-update/update-gradle-wrapper-action#335]
How do I exclude a wrapper path? I manage a gradle plugin and have some projects that need to use old wrappers to check for backwards compatibility. Is there a way to exclude these projects/paths?

**Comment by etiennestuder** [comment]
@cristiangreco we are running into the same problem at Gradle:
https://github.com/gradle/gradle-enterprise-build-config-samples/runs/4819364636?check_suite_focus=true

Any chance you can provide a feature to exclude certain paths?

**Comment by cristiangreco** [comment]
Hi @etiennestuder, love to see this is used at Gradle :)

I got something on a branch, will try to polish it in the next few days.

**Comment by etiennestuder** [comment]
Thanks. Sounds promising. That would remove 1 of the 2 blockers we are facing.

**Comment by cristiangreco** [comment]
As of release `v1.0.17` this can be accomplished with the new [`paths-ignore`](https://github.com/gradle-update/update-gradle-wrapper-action#paths-ignore) input param. The `v1` tag is up-to-date with latest release, so you can continue to use it (recommended).

**Comment by etiennestuder** [comment]
Thanks, @cristiangreco
