### ISSUE TITLE
Unexpected input 'pr-title-template'

### ISSUE THREAD

**Issue by sumanmaity112** [gradle-update/update-gradle-wrapper-action#732]
I have recently started using _**update-gradle-wrapper-action**_ to automatically update the gradle wrapper. As part of workflow, I used `pr-title-template` to customize pull request template as per documentation but currently I am getting the following warning
```
Warning: Unexpected input(s) 'pr-title-template', valid inputs are ['repo-token', 'reviewers', 'team-reviewers', 'labels', 'base-branch', 'target-branch', 'set-distribution-checksum', 'paths', 'paths-ignore', 'release-channel', 'merge-method']
Run gradle-update/update-gradle-wrapper-action@v1
  with:
    labels: dependencies, gradle
    pr-title-template: chore: Bump Gradle Wrapper from %sourceVersion% to %targetVersion%
    repo-token: ***
    set-distribution-checksum: true
    release-channel: stable
```

Here is my [complete workflow](https://github.com/sumanmaity112/java-starter/blob/5d40909/.github/workflows/update-gradle-wrapper.yml).

**Comment by SimonMarquis** [comment]
Unfortunately, there was no new release since PR #695
@cristiangreco is this something that you would be willing to do in the near future?

**Comment by cristiangreco** [comment]
Hi, v2 is now released, it includes the `pr-title-template` input param. Thanks for your patience 🙏
