### ISSUE TITLE
Please release v2.0.0 of this GitHub Action to release node20 change

### ISSUE THREAD

**Issue by ChrisCarini** [gradle-update/update-gradle-wrapper-action#823]
Hi @cristiangreco ,

When you have a few minutes, can you please create a new release based off the current `master` branch, specifically to pick up the change by @chadlwilson in https://github.com/gradle-update/update-gradle-wrapper-action/pull/802 to fully close out https://github.com/gradle-update/update-gradle-wrapper-action/issues/800.

As a related aside, if you'd like help maintaining this repository, I'd like to offer my help; next to dependabot & you, I'm ranked 3rd for contributors to this repository (https://github.com/gradle-update/update-gradle-wrapper-action/graphs/contributors ; with a total of 2 commits to this repo, wow. ik.). I've happily given several PRs reviews in the past, and am happy to help review the others as well. Let me know.

Best,
Chris Carini

**Comment by cristiangreco** [comment]
Hi Chris, v2 is now released.

Thanks so much for your help and proactivity, hope you'll continue to contribute :)

**Comment by ChrisCarini** [comment]
Hi Christian - thank you for releasing v2; I've been using it in several of my repos since release, and it's been completely stable for me. ✅ 

No problem - glad to help! My offer will remain, if you are interested (now or in the future), just get in touch!
