### ISSUE TITLE
Push uses GITHUB_TOKEN not provided repo_token

### ISSUE THREAD

**Issue by huehnerlady** [gradle-update/update-gradle-wrapper-action#83]
We ran into the issue, that even with a PAT the ci checks are not triggered when using the push event. This means so far we cannot use this action unfortunately as we use the push event to trigger our ci checks rather than the pull_request event. This has multiple reasons, among it is that we want to trigger the checks already before the pull request has been opened.

From GitHub Support we got the following:
> While investigating the source code for the gradle-update/update-gradle-wrapper-action Action our engineers found that it doesn't use the Personal Access Token that you've provided when pushing changes.
> 
> The changes are pushed using the authentication that's set up by actions/checkout, which is GITHUB_TOKEN.

Could you fix that so it uses the handed in token for everything and so would also trigger a push event?

**Comment by cristiangreco** [comment]
Thanks for reporting this @huehnerlady, I'll have a look at it in the next few days.

**Comment by huehnerlady** [comment]
@cristiangreco happy new year. Do you maybe have an update for this issue?

**Comment by cristiangreco** [comment]
Hey @huehnerlady sorry for not being active on this bug. I'm working on previously reported issues and hope to be able to work on this one either this week or next week.

**Comment by huehnerlady** [comment]
@cristiangreco ok, thanks for the update :)

**Comment by cristiangreco** [comment]
@huehnerlady I'm looking into this bug and wanted to be sure to be able to reproduce the described scenario correctly. Do you have an example setup or a public repo that I can have a look at?

**Comment by cristiangreco** [comment]
@huehnerlady actually, I think I managed to reproduce the issue and have an idea how to fix it. I also think that the following workaround should work in case you're willing to give it a try: configure the `checkout` action with the `token` parameter set to the same PAT token used for the Update Gradle Wrapper action, as in

```yml
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
```

Would you be able to report back whether this work for your scenario?

**Comment by huehnerlady** [comment]
@cristiangreco I tested your suggestion and that works. Is there a way to fix it inside the wrapper-action or is this a restriction of github and therefore this workaround is needed?

**Comment by cristiangreco** [comment]
@huehnerlady thanks for testing the workaround. This is fixable on the UGW action so you won't need to keep it around forever. Will work on it.

**Comment by huehnerlady** [comment]
@cristiangreco super cool, thanks. Happy to help with testing, just ask :)

**Comment by cristiangreco** [comment]
@huehnerlady I believe this behaviour is fixed now. I haven't cut a new release yet as I want to get some other changes merged before release. However, you can test it by (temporarily) pointing to `master` instead of `v1`:

```
uses: gradle-update/update-gradle-wrapper-action@master
```

**Comment by huehnerlady** [comment]
@cristiangreco super cool, it works. Do you have an idea when you will do the release? Like a few days, few weeks/months?

**Comment by cristiangreco** [comment]
I'm planning to cut the new release by tomorrow. The change I want to get in is making `repo-token` not mandatory anymore, which requires just a bit of testing and docs updates.

**Comment by huehnerlady** [comment]
@cristiangreco thanks, as it is less than a few weeks I will wait for the release then before implementing one of the 2 workarounds :) 

Looking forward to using it 🎉

**Comment by cristiangreco** [comment]
@huehnerlady I've cut a new release and updated the `v1` tag. Would you be able to test again with the usual setup?

```yml
uses: gradle-update/update-gradle-wrapper-action@v1
```

Thanks!

**Comment by huehnerlady** [comment]
@cristiangreco Many thanks, it is all fixed now. 
That means we can reenable the action in our repositories now, many thanks :)

**Comment by cristiangreco** [comment]
Thanks for your help, closing it now.
